version: '3.7'

services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go/app:/go/src/app
    ports:
      - 3000
    security_opt:
      - seccomp:unconfined
    command: bash -c "realize start --server"
  nginx:
    build:
      context: ./nginx
    ports:
      - 8888:80
    depends_on:
      - go
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
