version: '3.7'

services:
  go01:
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go/app:/go/src/app
    ports:
      - 3000
    security_opt:
      - seccomp:unconfined
    command: bash -c "realize start --server"
  go02:
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go/app:/go/src/app
    ports:
      - 3000
    security_opt:
      - seccomp:unconfined
    command: bash -c "realize start --server"
  go03:
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go/app:/go/src/app
    ports:
      - 3000
    security_opt:
      - seccomp:unconfined
    command: bash -c "realize start --server"
  nginx_proxy:
    build:
      context: ./nginx
    ports:
      - 8888:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  nginx_origin:
    build:
      context: ./nginx_origin
    ports:
      - 18888:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
